import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
    <Navbar />
      <Head>
        <title>Retroview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Retroview
        </h1>

        <div className={styles.grid}>
          <a href="/interviews" className={styles.card}>
            <h2>Interviews </h2>
            <p>View and add to your own list of interviews!</p>
          </a>

          <a href="/skills" className={styles.card}>
            <h2>Skills </h2>
            <p>Continue honing those skills and turn those boxes green!</p>
          </a>
        </div>
      </main>

    </div>
  )
}
